### ISSUE TITLE
[V1.3] Unable to perform add command properly

### ISSUE THREAD

**Issue by AhmadAlkaff** [CS2103AUG2017-F10-B4/main#76]
This command "add n/Betsy Crowe t/friend e/betsycrowe@example.com a/Newgate Prison p/1234567 t/criminal" does not work

**Comment by AhmadAlkaff** [comment]
<img width="1280" alt="screen shot 2017-11-03 at 3 01 08 pm" src="https://user-images.githubusercontent.com/31032813/32362975-dd602802-c0a7-11e7-870a-f481469d0519.png">

**Comment by AhmadAlkaff** [comment]
Update user guide for Birthday field

**Comment by aver1493** [comment]
Hi, thanks for your feedback! If you tried on v1.3.jar it probably won't work! It works in v1.4.jar!
<img width="1302" alt="screen shot 2017-11-03 at 6 19 46 pm" src="https://user-images.githubusercontent.com/31089929/32369363-e0eb3950-c0c3-11e7-885f-fd9e274ac4ce.png">
